/* Generated By:JavaCC: Do not edit this line. RegrasConstants.java */
package de.fxe.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RegrasConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int GENE = 5;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<GENE>",
    "\"+\"",
    "\"(\"",
    "\")\"",
    "\",\"",
  };

}
